# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 15:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockProfileModel',
            fields=[
                ('tickerName', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('fullName', models.CharField(max_length=50)),
                ('companyOverview', models.CharField(max_length=2000)),
                ('founded', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='StockStatusModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('highPrice', models.DecimalField(decimal_places=2, max_digits=8)),
                ('lowPrice', models.DecimalField(decimal_places=2, max_digits=8)),
                ('currentPrice', models.DecimalField(decimal_places=2, max_digits=8)),
                ('whichStock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.StockProfileModel')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amountSpent', models.DecimalField(decimal_places=2, max_digits=8)),
                ('numberPurchased', models.IntegerField()),
                ('datePurchased', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('whichStock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.StockProfileModel')),
            ],
        ),
    ]
