# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 15:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockprofilemodel',
            old_name='companyOverview',
            new_name='overview',
        ),
    ]
