# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 01:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks', '0002_auto_20171103_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messageTitle', models.CharField(max_length=200)),
                ('messageBody', models.CharField(max_length=2000)),
                ('datePosted', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
