# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_auto_20171108_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockprofilemodel',
            name='category',
            field=models.CharField(default='Technology', max_length=50),
            preserve_default=False,
        ),
    ]
